// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmaGKeJndKboXT_uLctLmREkPXzXTwkls',
    appId: '1:105905235168:web:6b21c21c91a0468daddc85',
    messagingSenderId: '105905235168',
    projectId: 'lifesync-ai-ca9d4',
    authDomain: 'lifesync-ai-ca9d4.firebaseapp.com',
    storageBucket: 'lifesync-ai-ca9d4.firebasestorage.app',
    measurementId: 'G-38J3JZCEE1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBcxw1gqZf_fGo0PjBGYZUrAUk6faaEQk',
    appId: '1:105905235168:android:ba0e7dd74d906542addc85',
    messagingSenderId: '105905235168',
    projectId: 'lifesync-ai-ca9d4',
    storageBucket: 'lifesync-ai-ca9d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm6xniCeIuU_NMOjThcXdWZbeVT5hqXQw',
    appId: '1:105905235168:ios:d3e97642b74eebd6addc85',
    messagingSenderId: '105905235168',
    projectId: 'lifesync-ai-ca9d4',
    storageBucket: 'lifesync-ai-ca9d4.firebasestorage.app',
    iosBundleId: 'com.example.lifesyncAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm6xniCeIuU_NMOjThcXdWZbeVT5hqXQw',
    appId: '1:105905235168:ios:d3e97642b74eebd6addc85',
    messagingSenderId: '105905235168',
    projectId: 'lifesync-ai-ca9d4',
    storageBucket: 'lifesync-ai-ca9d4.firebasestorage.app',
    iosBundleId: 'com.example.lifesyncAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmaGKeJndKboXT_uLctLmREkPXzXTwkls',
    appId: '1:105905235168:web:fec18e1c86d8d0b9addc85',
    messagingSenderId: '105905235168',
    projectId: 'lifesync-ai-ca9d4',
    authDomain: 'lifesync-ai-ca9d4.firebaseapp.com',
    storageBucket: 'lifesync-ai-ca9d4.firebasestorage.app',
    measurementId: 'G-627Y88N98Q',
  );
}
